export const routesData = [
  {
    min: 1300,
    max: 1390,
    category: "EIP",
    vmax: 200,
    time: "02:38",
    origin: "Warszawa Wschodnia",
    destination: "Kraków Płaszów",
    spawnStart: "Warszawa Grochów",
    spawnEnd: "Kraków Płaszów",
  },
  {
    min: 3100,
    max: 3190,
    category: "EIP",
    vmax: 200,
    time: "02:42",
    origin: "Kraków Płaszów",
    destination: "Warszawa Wschodnia",
    spawnStart: "Kraków Płaszów",
    spawnEnd: "Warszawa Grochów",
  },
  {
    min: 1400,
    max: 1490,
    category: "EIP",
    vmax: 200,
    time: "02:36",
    origin: "Warszawa Wschodnia",
    destination: "Bielsko-Biała Główna",
    spawnStart: "Warszawa Grochów",
    spawnEnd: "Brynów",
  },
  {
    min: 4100,
    max: 4490,
    category: "EIP",
    vmax: 200,
    time: "02:39",
    origin: "Gliwice",
    destination: "Warszawa Wschodnia",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Warszawa Grochów",
  },
  {
    min: 5400,
    max: 5490,
    category: "EIP",
    vmax: 200,
    time: "02:26",
    origin: "Gdynia Główna",
    destination: "Gliwice",
    spawnStart: "Warszawa Praga",
    spawnEnd: "Katowice Towarowa KTC",
  },
  {
    min: 4500,
    max: 4990,
    category: "EIP",
    vmax: 200,
    time: "02:35",
    origin: "Bielsko-Biała Główna",
    destination: "Gdynia Główna",
    spawnStart: "Brynów",
    spawnEnd: "Warszawa Praga",
  },
  {
    min: 1600,
    max: 1690,
    category: "EIP",
    vmax: 200,
    time: "01:36",
    origin: "Warszawa Wschodnia",
    destination: "Jelenia Góra",
    spawnStart: "Warszawa Grochów",
    spawnEnd: "Żelisławice",
  },
  {
    min: 6100,
    max: 6190,
    category: "EIP",
    vmax: 200,
    time: "01:39",
    origin: "Jelenia Góra",
    destination: "Warszawa Wschodnia",
    spawnStart: "Żelisławice",
    spawnEnd: "Warszawa Grochów",
  },
  //
  {
    min: 7300,
    max: 7399,
    category: "EIE",
    vmax: 120,
    time: "00:30",
    origin: "Poznań Główny",
    destination: "Kraków Płaszów",
    spawnStart: "Myszków",
    spawnEnd: "Sosnowiec Maczki",
  },
  {
    min: 3700,
    max: 3799,
    category: "EIE",
    vmax: 120,
    time: "00:31",
    origin: "Kraków Płaszów",
    destination: "Poznań Główny",
    spawnStart: "Sosnowiec Maczki",
    spawnEnd: "Myszków",
  },

  {
    min: 53000,
    max: 53999,
    category: "MPE",
    vmax: 140,
    time: "03:06",
    origin: "Gdynia Główna",
    destination: "Zakopane",
    spawnStart: "Warszawa Praga",
    spawnEnd: "Kraków Zabłocie",
  },
  {
    min: 35000,
    max: 35999,
    category: "MPE",
    vmax: 140,
    time: "03:07",
    origin: "Zakopane",
    destination: "Gdynia Główna",
    spawnStart: "Kraków Zabłocie",
    spawnEnd: "Warszawa Praga",
  },

  {
    min: 54000,
    max: 54999,
    category: "ECE",
    vmax: 140,
    time: "03:14",
    origin: "Gdynia Główna",
    destination: "Bohumin",
    spawnStart: "Warszawa Praga",
    spawnEnd: "Brynów",
  },
  {
    min: 45000,
    max: 45999,
    category: "ECE",
    vmax: 140,
    time: "03:08",
    origin: "Bohumin",
    destination: "Gdynia Główna",
    spawnStart: "Brynów",
    spawnEnd: "Warszawa Praga",
  },
  {
    min: 16100,
    max: 16500,
    category: "MPE",
    vmax: 140,
    time: "01:57",
    origin: "Warszawa Wschodnia",
    destination: "Jelenia Góra",
    spawnStart: "Warszawa Grochów",
    spawnEnd: "Żelisławice",
  },
  {
    min: 61100,
    max: 61500,
    category: "MPE",
    vmax: 140,
    time: "02:17",
    origin: "Jelenia Góra",
    destination: "Warszawa Wschodnia",
    spawnStart: "Żelisławice",
    spawnEnd: "Warszawa Grochów",
  },
  {
    min: 23100,
    max: 23499,
    category: "MPE",
    vmax: 120,
    time: "00:55",
    origin: "Kielce",
    destination: "Kraków Płaszów",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Kraków Płaszów",
  },
  {
    min: 32100,
    max: 32499,
    category: "MPE",
    vmax: 120,
    time: "00:57",
    origin: "Kraków Płaszów",
    destination: "Kielce",
    spawnStart: "Kraków Płaszów",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 24100,
    max: 24149,
    category: "MPE",
    vmax: 120,
    time: "01:40",
    origin: "Lublin",
    destination: "Gliwice",
    spawnStart: "Czarnca",
    spawnEnd: "Katowice Towarowa KTC",
  },
  {
    min: 42100,
    max: 42149,
    category: "MPE",
    vmax: 120,
    time: "01:42",
    origin: "Gliwice",
    destination: "Lublin",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Czarnca",
  },
  {
    min: 24150,
    max: 24203,
    category: "MPE",
    vmax: 120,
    time: "01:56",
    origin: "Kielce",
    destination: "Gliwice",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Katowice Towarowa KTC",
  },
  {
    min: 42150,
    max: 42300,
    category: "MPE",
    vmax: 120,
    time: "01:42",
    origin: "Gliwice",
    destination: "Skarżysko-Kamienna",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Sędziszów Towarowy",
  },
  //
  {
    min: 23900,
    max: 23999,
    category: "MOJ",
    vmax: null,
    time: "01:23",
    origin: "Kielce",
    destination: "Kraków Płaszów",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Kraków Płaszów",
  },
  {
    min: 32900,
    max: 32999,
    category: "MOJ",
    vmax: null,
    time: "01:25",
    origin: "Kraków Płaszów",
    destination: "Kielce",
    spawnStart: "Kraków Płaszów",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 24900,
    max: 24990,
    category: "MOJ",
    vmax: null,
    time: "02:39",
    origin: "Kielce",
    destination: "Katowice Ligota",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Brynów",
  },
  {
    min: 42900,
    max: 42990,
    category: "MOJ",
    vmax: null,
    time: "02:15",
    origin: "Katowice Ligota",
    destination: "Kielce",
    spawnStart: "Brynów",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 40100,
    max: 40149,
    category: "S41",
    vmax: null,
    time: "01:05",
    origin: "Częstochowa",
    destination: "Tychu Lodowisko",
    spawnStart: "Myszków",
    spawnEnd: "Brynów",
  },
  {
    min: 40650,
    max: 40700,
    category: "S41",
    vmax: null,
    time: "01:13",
    origin: "Tychy Lodowisko",
    destination: "Częstochowa",
    spawnStart: "Brynów",
    spawnEnd: "Myszków",
  },
  {
    min: 40150,
    max: 40200,
    category: "S1",
    vmax: null,
    time: "01:03",
    origin: "Gliwice",
    destination: "Częstochowa",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Myszków",
  },
  {
    min: 40600,
    max: 40649,
    category: "S1",
    vmax: null,
    time: "01:20",
    origin: "Częstochowa",
    destination: "Gliwice",
    spawnStart: "Myszków",
    spawnEnd: "Katowice Towarowa KTC",
  },

  {
    min: 19700,
    max: 19790,
    category: "R3",
    vmax: null,
    time: "00:32",
    origin: "Zielonka",
    destination: "Ożarów Mazowiecki",
    spawnStart: "Warszawa Podskarbińska",
    spawnEnd: "Warszawa Gołąbki",
  },
  {
    min: 91700,
    max: 91790,
    category: "R3",
    vmax: null,
    time: "00:31",
    origin: "Ożarów Mazowiecki",
    destination: "Zielonka",
    spawnStart: "Warszawa Gołąbki",
    spawnEnd: "Warszawa Podskarbińska",
  },

  {
    min: 19800,
    max: 19990,
    category: "R1",
    vmax: null,
    time: "01:08",
    origin: "Warszawa Wschodnia",
    destination: "Skierniewice",
    spawnStart: "Warszawa Grochów",
    spawnEnd: "Żyrardów",
  },
  {
    min: 91800,
    max: 91990,
    category: "R1",
    vmax: null,
    time: "01:06",
    origin: "Skierniewice",
    destination: "Warszawa Wschodnia",
    spawnStart: "Żyrardów",
    spawnEnd: "Warszawa Grochów",
  },

  // CARGO
  {
    min: 132000,
    max: 133000,
    category: "TDE",
    vmax: 100,
    time: "04:16",
    origin: "Warszawa Gł.Tow. WOA",
    destination: "Kraków Nowa Huta NHA",
    spawnStart: "Warszawa Główna Towarowa",
    spawnEnd: "Dłubnia",
  },
  {
    min: 144200,
    max: 144299,
    category: "TME",
    vmax: 80,
    time: "02:18",
    origin: "Radom",
    destination: "Tychy",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Staszic",
  },
  {
    min: 144300,
    max: 144399,
    category: "TME",
    vmax: 80,
    time: "01:54",
    origin: "Skarżysko-Kamienna",
    destination: "Jaworzno Szczakowa",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Borowa Górka",
  },
  {
    min: 412000,
    max: 412900,
    category: "TDE",
    vmax: 100,
    time: "03:41",
    origin: "Jaworzno Szczakowa",
    destination: "Łódź Chojny",
    spawnStart: "Sosnowiec Maczki",
    spawnEnd: "Radzice",
  },
  {
    min: 424000,
    max: 424098,
    category: "TME",
    vmax: 80,
    time: "02:20",
    origin: "Katowice Much. Staszic",
    destination: "Sitkówka Nowiny",
    spawnStart: "Katowice Muchowiec Staszic",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 424100,
    max: 424198,
    category: "TME",
    vmax: 80,
    time: "01:20",
    origin: "Jaworzno Szczakowa",
    destination: "Wolica",
    spawnStart: "Borowa Górka",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 234000,
    max: 235000,
    category: "TME",
    vmax: 100,
    time: "01:20",
    origin: "Kielce",
    destination: "Brzesko Okocim",
    spawnStart: "Sędziszów Towarowy",
    spawnEnd: "Kraków Olsza",
  },
  {
    min: 324000,
    max: 325000,
    category: "TME",
    vmax: 100,
    time: "01:12",
    origin: "Brzesko Okocim",
    destination: "Jędrzejów",
    spawnStart: "Kraków Olsza",
    spawnEnd: "Sędziszów Towarowy",
  },
  {
    min: 441000,
    max: 441990,
    category: "TRE",
    vmax: 80,
    time: "01:33",
    origin: "Częstochowa Towarowa",
    destination: "Tychy Fiat",
    spawnStart: "Myszków",
    spawnEnd: "Staszic",
  },
  {
    min: 443000,
    max: 443990,
    category: "TKE",
    vmax: 90,
    time: "01:14",
    origin: "Dąbrowa Górnicza Tow.",
    destination: "Częstochowa Mirów",
    spawnStart: "Dąbrowa Górnicza Towarowa",
    spawnEnd: "Myszków",
  },
  {
    min: 344000,
    max: 345000,
    category: "TME",
    vmax: 100,
    time: "02:01",
    origin: "Wola Rzędzińska",
    destination: "Chorzew Siemkowice",
    spawnStart: "Kraków Olsza",
    spawnEnd: "Koniecpol",
  },
  {
    min: 444000,
    max: 445000,
    category: "TME",
    vmax: 100,
    time: "02:56",
    origin: "Chorzew Siemkowice",
    destination: "Sosnowiec Jęzor",
    spawnStart: "Koniecpol",
    spawnEnd: "Sosnowiec Maczki",
  },
  {
    min: 445000,
    max: 445490,
    category: "TSE",
    vmax: 50,
    time: "01:43",
    origin: "Trzebinia",
    destination: "Częstochowa Towarowa",
    spawnStart: "Sosnowiec Maczki",
    spawnEnd: "Myszków",
  },
  {
    min: 464000,
    max: 465000,
    category: "TME",
    vmax: 80,
    time: "01:52",
    origin: "Katowice Much. Staszic",
    destination: "Wrocław Nadodrze",
    spawnStart: "Katowice Muchowiec Staszic",
    spawnEnd: "Myszków",
  },
  {
    min: 649000,
    max: 650000,
    category: "ZXE",
    vmax: 80,
    time: "01:40",
    origin: "Piława Górna",
    destination: "Myszków",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Myszków",
  },
  {
    min: 649000,
    max: 650000,
    category: "ZXE",
    vmax: 80,
    time: "01:40",
    origin: "Piława Górna",
    destination: "Myszków",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Myszków",
  },
  {
    min: 335001,
    max: 335100,
    category: "LTE",
    vmax: 100,
    time: "00:07",
    origin: "Kraków Nowa Huta NHEO",
    destination: "Kraków Olsza",
    spawnStart: "Dłubnia",
    spawnEnd: "Kraków Olsza",
  },

  {
    min: 445500,
    max: 445590,
    category: "LTE",
    vmax: 100,
    time: "01:42",
    origin: "Sosnowiec Maczki",
    destination: "Myszków",
    spawnStart: "Sosnowiec Maczki",
    spawnEnd: "Myszków",
  },
  {
    min: 446000,
    max: 447000,
    category: "PWJ",
    vmax: 100,
    time: "02:21",
    origin: "Częstochowa",
    destination: "Tychy",
    spawnStart: "Myszków",
    spawnEnd: "Staszic",
  },
  {
    min: 336001,
    max: 336100,
    category: "LTE",
    vmax: 100,
    time: "00:12",
    origin: "Kraków Nowa Huta NHEO",
    destination: "Kraków Płaszów",
    spawnStart: "Dłubnia",
    spawnEnd: "Kraków Płaszów",
  },
];

export const routesDataAlt = [
  {
    min: 335000,
    max: 335100,
    category: "LTE",
    vmax: 100,
    time: "00:07",
    origin: "Kraków Olsza",
    destination: "Kraków Nowa Huta NHEO",
    spawnStart: "Kraków Olsza",
    spawnEnd: "Dłubnia",
  },
  {
    min: 336000,
    max: 336100,
    category: "LTE",
    vmax: 100,
    time: "00:14",
    origin: "Kraków Płaszów",
    destination: "Kraków Nowa Huta NHEO",
    spawnStart: "Kraków Płaszów",
    spawnEnd: "Dłubnia",
  },
  {
    min: 24205,
    max: 24210,
    category: "MPE",
    vmax: 120,
    time: "01:40",
    origin: "Lublin",
    destination: "Gliwice",
    spawnStart: "Czarnca",
    spawnEnd: "Katowice Towarowa KTC",
  },
  {
    min: 42200,
    max: 42202,
    category: "MPE",
    vmax: 120,
    time: "01:42",
    origin: "Gliwice",
    destination: "Lublin",
    spawnStart: "Katowice Towarowa KTC",
    spawnEnd: "Czarnca",
  },
];
